sample_instance: False
num_instances: 8
batch_size: 90
height: 256
width: 128
model: resnet_channel2
depth: 50
num_features: 512
dropout: 0.0

loss_type: multi


theta: 0.1
sac: True


gamma: 1.0
xen: True




alpha: 1.0
trip: False
margin1: 0.5



beta: 1.0
pnsm_weight: False
pnsm_com: False
quad: False

margin2: 0.2

weight_margin: 2.0
pnsm_pos_radius_divide: 2.0
pnsm_neg_radius_divide: 2.0


optimizer: sgd
lr: 0.1
resume: False
frozen_sublayer: True
