dataset: market1501
sample_instance: False
num_instances: 8
batch_size: 256
height: 256
width: 128
model: resnet_channel
depth: 50
num_features: 1024
dropout: 0.0

loss_type: single


theta: 0.1
sac: True


gamma: 1.0
xen: True




alpha: 1.0
trip: False
margin1: 0.5



beta: 1.0
trip_weight: False
trip_com: False
quad: False

margin2: 0.2

weight_margin: 2.0
trip_weight_pos_radius_divide: 2.0
trip_weight_neg_radius_divide: 2.0


optimizer: sgd
lr: 0.1
resume: False
frozen_sublayer: True
